---

- name: Adapt ASCS profile to prevent sapsrv from restarting it
  replace:
    path: '{{ sap_netweaver_ha_pacemaker_profile_file_ascs }}'
    backup: yes
    regexp: 'Restart'
    replace: 'Start'

- name: Adapt ERS profile to prevent sapsrv from restarting it
  replace:
    path: '{{ sap_netweaver_ha_pacemaker_profile_file_ers }}'
    backup: yes
    regexp: 'Restart'
    replace: 'Start'

- name: Remove 'Autostart' from ERS profile
  replace:
    path: /usr/sap/sapservices
    backup: yes
    regexp: '(Autostart*)'
    replace: '#\1'

- name: Configure Keep Alive
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 300

- name: Update /usr/sap/services
  replace:
    path: /usr/sap/sapservices
    backup: yes
    regexp: '(LD_LIBRARY*)'
    replace: '#\1'